### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Mynock17** [luvit/luvit#1034]
We are searching for a platform for our next project. Luvit looks very promising - however we are a little bit scared because the last release was one year ago: LuaJIT is 2.0.4, Links are broken (API), Documentation is weak ...

**Comment by SinisterRectus** [comment]
There isn't currently any active development, but issues are addressed when they appear. I'm not sure why the API page is dead. The docs are indeed weak, but there is a wealth of information available found in the source code, examples, and a few blog posts.

**Comment by creationix** [comment]
It's alive, but I don't think anyone is working on it full time.  I for one have neglected most my open source projects in the last year due to lots of family and work responsibilities.

That said, luvit is one of my favorite projects and I'd like to see it continue to live on, it's still used in a few places and I recently had great success using it at one of my contract jobs where they needed some network services implemented very quickly for satellite operating systems.

**Comment by sousoux** [comment]
I did a major project using luvit which is still very much alive today. I'd
highly recommended it and the small community around it.

**Comment by Dog2puppy** [comment]
I'm using Luvit to write a matchmaking server for a game I'm making. I think Luvit could one day have a community like Node.js.

**Comment by Miigon** [comment]
I have used luvit for making server software prototypes for quite a few times and I thought it's even more powerful and easy than doing the same thing in Python.
