### ISSUE TITLE
Attempting to run the FFI's "Hello World" example (from luajit.org) results in an error when using luvit, but works in luajit (?)

### ISSUE THREAD

**Issue by Duckwhale** [luvit/luvit#1152]
So I've been trying to learn more about Lua/C interactions, and to start simple I attempted to run the easiest example I could find. 
The code is taken from http://luajit.org/ext_ffi.html directly:

```lua
local ffi = require("ffi")

-- Works ONLY when using luajit
ffi.cdef [[
	int printf(const char *fmt, ...);
	]]

ffi.C.printf("Hello %s!", "world")

```

To my surprise, it didn't work when using ``luvit`` to run the script, raising the following error:

![image](https://user-images.githubusercontent.com/16489133/127553437-afb2ab73-70ff-473a-aee0-d630423b878c.png)

However, if I run the same code using ``luajit``, it works as expected. Did I do something wrong?

I also tried running the second example, and it works in ``luvit`` as well as ``luajit``:

```lua
local ffi = require("ffi")
ffi.cdef[[
int MessageBoxA(void *w, const char *txt, const char *cap, int type);
]]
ffi.C.MessageBoxA(nil, "Hello world!", "Test", 0)
```

Additional information:

![image](https://user-images.githubusercontent.com/16489133/127554135-739952fc-58a0-4957-98d0-eabf0f2b5f46.png)

![image](https://user-images.githubusercontent.com/16489133/127554165-d31e0988-cd01-4abe-a03c-25865f5f15d2.png)

**Comment by Bilal2453** [comment]
Works for me on Linux: 
![image](https://user-images.githubusercontent.com/38175840/127554497-83097309-b8f9-4ff9-a938-e69ea3e525b2.png)

**Comment by SinisterRectus** [comment]
Are you running this on Windows? You need to load msvcrt.

```lua
local C = ffi.os == "Windows" and ffi.load("msvcrt") or ffi.C
```

**Comment by Duckwhale** [comment]
Yes, that's on Windows. Attempting to load the runtime didn't change anything, though.

Are there differences in how Luvit searches for files included via ``ffi`` or does ``luajit`` have something it doesn't? Seems like a strange issue to face, but then I don't understand how things work internally yet.

**Comment by Bilal2453** [comment]
Luvit has absolutely nothing to do with FFI at all, all of this is completely handled by LuaJIT itself, the one included into the Luvit binary. So it doesn't really make sense that the same version of LuaJIT works when the other does not.

Though, I can't really make sure of any of this, since it looks like it only happen on Windows I assume.

**Comment by SinisterRectus** [comment]
I believe that you have to do this due to the way luvi is compiled for Windows. This trick works on my machine, so I'm not sure what's wrong for you.
![image](https://user-images.githubusercontent.com/11720541/127680468-939c5e9c-8552-466f-892d-312b64c059fe.png)

Are you sure you're using the user-defined `C` and not `ffi.C` when testing?

**Comment by Duckwhale** [comment]
> Are you sure you're using the user-defined C and not ffi.C when testing?

Apparently I wasn't. It's working now, thank you! (Small victories :joy: )
