### ISSUE TITLE
Request: NixOS package for integrate with Repl.it

### ISSUE THREAD

**Issue by lajbel** [luvit/luvit#1162]
It would be great to be able to use luvit on Replit.com, you could if they had a nixOS package!

**Comment by Bilal2453** [comment]
Luvit can already work on `replit.com`. Nothing special needed here to make it work, although indeed a nix package could make it easier but if we were to port Luvit to any package manager we would do this for the more-used package managers first. So as of now, I don't think that is a good idea (and it is not like installing it manually on replit is hard).

Good luck.

**Comment by Duckwhale** [comment]
In Unix environments, typing ``luvit`` will *not* run the executable from your current working directory automatically ([for security reasons](https://stackoverflow.com/questions/6331075/why-do-you-need-dot-slash-before-executable-or-script-name-to-run-it-in-bas)). That's why you have to prepend it with a dot (``.``, for "current working directory"): ``./luvit`` should run it if you're in the folder where it's located.

Or you could simply type ``bin/luvit`` instead of ``luvit`` if the folder layout as as pictured above.
