### ISSUE TITLE
Coding conventions: optional argument in the middle

### ISSUE THREAD

**Issue by hnakamur** [luvit/luvit#295]
In node.js, we can write something like fs.open('foo.txt', 'r', callback),
in which the mode argument is omitted and the callback argument is passed.
http://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback

In the JavaScript world, especially jQuery, this is a common style.
I followed this style in
https://github.com/hnakamur/luvit/commit/e6afd7ce805943af19525b53f1dad5f015e60298

However, this complicates the implementation and slow down functions to run.
I prefer to passing nil for default values like:
fs.open('foo.txt', 'r', nil, callback)

In this way we can simply write in function definitions like:
function fs.open(path, flag, mode, callback)
  if mode == nil then mode = tonumber('666', 8) end
  ...
end

What do you think?

**Comment by creationix** [comment]
I don't like having `nil` placeholders.  I'm moving more and more towards coroutine based programming which doesn't have this problem since there is no callback in tail of the arguments.

As far as the node-style APIs, we should try to mirror whatever syntax node uses since the entire goal there is to ease migration of node people to using luvit.
