### ISSUE TITLE
Add support for Mobdebug to support debugging

### ISSUE THREAD

**Issue by rphillips** [luvit/luvit#642]
https://github.com/pkulchenko/MobDebug

**Comment by halfnelson** [comment]
Managed to get mobdebug working okay with luvi by adding a cmake option to compile in luasocket 3.0
see last two commits https://github.com/halfnelson/luvi/tree/feature/luasocket

**Comment by creationix** [comment]
I wonder how luasocket affects the libuv event loop.  I'm concerned about baking luasocket into core luvi.

**Comment by halfnelson** [comment]
I looked at the luasocket source and couldn't see anything that would interfere with the uv event loop. Apart from the fact it would hold it up on request/response due to its blocking nature. 
I don't think luasocket should be part of luvi either, in my fork i only enable it for debug builds. My next step was to try get it compiling as a shared library so that mobdebug an just require it in.

I got a decent distance in replicating luasockets api with coro-net, until I discovered that luajit 2.0 can't yield from a debug hook, which made my coro-net based luasocket lib unusable in debugging context.

**Comment by halfnelson** [comment]
Fwiw mobdebug works okay with libuv, I managed to set breakpoints in a createserver call and before and after the read operations with no problems.

**Comment by creationix** [comment]
Cool, good luck.

**Comment by SinisterRectus** [comment]
@halfnelson Try disabling jit with `jit.off([fn])` before using the hook.
