### ISSUE TITLE
luvit -n shows hello message in color

### ISSUE THREAD

**Issue by radare** [luvit/luvit#679]
wat

**Comment by creationix** [comment]
It appears the `-n`, `-c` and `-C` flags are broken.

**Comment by creationix** [comment]
For anyone wanting to tackle this issue, the problem is most likely in https://github.com/luvit/luvit/blob/master/main.lua where it's not setting the color more properly when handling the arguments.  If it's not there, then it's an issue in pretty-print perhaps around https://github.com/luvit/luvit/blob/master/deps/pretty-print/init.lua#L115-L119.
