### ISSUE TITLE
I wan't to make luvit as a lua module works without LuaJIT.

### ISSUE THREAD

**Issue by xpol** [luvit/luvit#682]
I love the async API for luvit/nodejs.

I have a games that already have Lua 5.1 (Not always LuaJIT) VM and APIs for game engine.
I'd like to have luvit APIs used in my game.

I want make luvit as a module works with exist Lua VM rather than luvit.exe

The follow 2 things needs to be done:
1. remove needs of `ffi`, buffer.lua and require.lua (require.lua only use ffi.os)
2. the module system is NodeJS style `exports`, should warped with local exports = {}; ... ; return exports.

Did I forget some thing? Any suggestions?

**Comment by imzyxwvu** [comment]
The most important thing is when to call uv.run(). luvit has hide the call to it just like node. Since what you use luvit in is a video game you have to call uv.run() with UV_RUN_NOWAIT (to make uv.run not block) inside your main loop before you update game varibles. 

> the module system is NodeJS style exports, should warped with local exports = {}; ... ; return exports.

luvit has already provided the exports table. Simply wrapping Lua library would cause syntax issues if it contains a return in the main scope. luvit uses setfenv.

luajit and PUC lua 5.1 have almost the same C API but you would gain lots of advantages from luajit. Please consider switching to luajit.

**Comment by creationix** [comment]
If you want the async core of luvit, but don't want the node.js style require system or the hard dependence that's exactly why luv is available as a standalone project.  I even just published it to luarocks. https://rocks.moonscript.org/modules/creationix/luv

**Comment by xpol** [comment]
@imzyxwvu Thank you very much!  And what I exactly wan't is `luarcoks install luvit` :smile: 

@creationix Yes. Its me just create that luarocks support issue and pr in luv. Thank you very much!

**Comment by SinisterRectus** [comment]
Closing this old issue in favor of the slightly newer #870.
