### ISSUE TITLE
Differences to nodejs?

### ISSUE THREAD

**Issue by pyros2097** [luvit/luvit#730]
How is luvit compared to nodejs? Is is faster, uses less memory, dynamic code loading (lua)? Does coroutine support improve performance/parallelism like golang?

**Comment by creationix** [comment]
Memory overhead is much smaller, startup time is much quicker.  V8 vs luajit is a tough one since both are extremely fast JIT engines, but they do have their unique strengths.

The coroutines are like ES6 generators, but without `yield` and `function*` all over the place making calls to coroutines invisible.  I've been writing a lot of lua code using coroutines that allows you to block on I/O go style, but still keep the single-threaded event-loop in libuv happy and moving along.

**Comment by joerg-krause** [comment]
Furthermore, luvit supports the ARMv5 architecture whereas Node.js 0.12 does not.

**Comment by nihildeb** [comment]
@creationix you said:

> I've been writing a lot of lua code using coroutines that allows you to block on I/O go style, but still keep the single-threaded event-loop in libuv happy and moving along

can you point me to an example here? I am currently writing a lit module for nanomsg. I am calling send and recv with the DONTWAIT option, and using coroutines to busy loop poll the sockets. I added in a uv.timer to avoid taking all the resources. This is far from good. If there was a better way to do this I would be happy to know it.

**Comment by creationix** [comment]
The coroutines don't help fix busyloop, they just allow you to suspend the coroutine and then resume it later when something happens.  This works well with libuv being callback based under the hood.

For example, suppose this callback based function
```lua
doAsyncThing(param, function (err, result)
  assert(not err, err)
  p("result", result)
end)
```

With coroutines, you can do:

```lua
local function doThing(param)
  local thread = coroutine.running()
  doAsyncThing(param, function (err, result)
    if err then
      coroutine.resume(thread, nil, err)
    else
      coroutine.resume(thread, result)
    end
  end)
  return coroutine.yield()
end

local result = assert(doThing(param))
```
