### ISSUE TITLE
luasocket Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by luochong** [luvit/luvit#805]
![qq 20150826211428](https://cloud.githubusercontent.com/assets/1026392/9494245/82437bc2-4c37-11e5-8d3c-fcf1945f0cd7.png)
![qq 20150826211626](https://cloud.githubusercontent.com/assets/1026392/9494256/90884fa0-4c37-11e5-80e3-4a9491a1950d.png)

**Comment by creationix** [comment]
I've never used luasocket, but I imagine it's not playing nice with libuv's event loop.  Are you able to use the native network APIs in luvit instread?

**Comment by luochong** [comment]
i use redis-lua but it  dependencies for luasocket

**Comment by creationix** [comment]
Right, you're welcome to debug the segfault issue, I don't think that should be happening.  But even if the crash is fixed, I'm pretty sure luasocket's I/O model is not compatible with libuv and will destroy performance.  The best solution is to port redis-lua to use luvit's I/O primitives instead of luasocket.

Maybe an abstraction could be written them makes luvit look more like luasocket to ease such porting?

**Comment by luochong** [comment]
Thanks, I will use luvit's I/O implement redis client

**Comment by creationix** [comment]
@luochong did you ever make any progress porting to the luvit APIs?
