### ISSUE TITLE
Promises / futures

### ISSUE THREAD

**Issue by ghost** [luvit/luvit#827]
Does Luvit provide a way of creating promises or futures?

Due to the asynchronous nature of NodeJS I would assume this to be one of the most often used modules. But I cannot find anything really usable...
- https://github.com/AndrewTsao/luvit-future
  - Has not been touched in 3 years,
  - Is not compatible with lit and the Luvit 2.0 module system: AndrewTsao/luvit-future#1, but the change is trivial: luvit-future-luvit-2.0.patch
  - Is not compatible with tap: AndrewTsao/luvit-future#2, because it catches all `error()`s,
  - While all of NodeJS uses `on("eventtype", function(...) end)`, luvit-future uses `on(function(ok, val) end)`... (i.e. an `ok` parameter and one value only, instead of varargs)
  - The reason for splitting `Completer` from `Future` and some name choices are not quite clear...
- https://github.com/Olivine-Labs/promise
  - Not a Luvit module, but can be adapted easily: promise-luvit.patch
  - The dependency on "uuid" can also be easily worked around: promise-remove-uuid-dependency.patch
  - There is no real way to fulfil the promise from another thread. Something as crazy as this does not work for obvious reasons:

``` lua
function fetch(hostname, port, path)
        local value = nil
        local req = http.request({hostname=hostname, port=port, path=path}, function(res)
                res:on("data", function(chunk)
                        value = chunk
                end)
        end)
        req:done()

        local p = promise.create()
        local id = p:start(function() while not value do end return value end)
        return p, id
end
```
- https://github.com/ppissanetzky/AndThen
  - Not a Luvit module and it is not even Lua 5.2 compatible: ppissanetzky/AndThen#2
- `require("core").Emitter`
  - Perfect
  - It should be better documented how to add own methods to an object created this way.
- Lua coroutines
  - They would be great, if it could be guaranteed that the thread calling back was able to deal with its execution being interrupted for an unknown amount of time.
  - "Issues" with this approach were mentioned on IRC.

luvit-future-luvit-2.0.patch:

``` diff
diff --git a/modules/future.lua b/modules/future.lua
index b022e08..c64a807 100644
--- a/modules/future.lua
+++ b/modules/future.lua
@@ -134,9 +134,8 @@ local function wait(...)
   return completer:getFuture()
 end

-return {
-  Future = Future,
-  Completer = Completer,
-  wait = wait,
-}
-
+exports.name = "AndrewTsao/luvit-future"
+exports.version = "0.0.0"
+exports.Future = Future
+exports.Completer = Completer
+exports.wait = wait
```

promise-luvit.patch:

``` diff
diff --git a/src/init.lua b/src/init.lua
index 28a1089..8b4d563 100644
--- a/src/init.lua
+++ b/src/init.lua
@@ -65,6 +65,9 @@ function promise:first()
   end
 end

-return function()
+exports.name = "Olivine-Labs/promise"
+exports.version = "0.1"
+
+function exports.create()
   return setmetatable({threads = {}}, {__index=promise})
 end
```

promise-remove-uuid-dependency.patch:

``` diff
diff --git a/src/init.lua b/src/init.lua
index 28a1089..8b4d563 100644
--- a/src/init.lua
+++ b/src/init.lua
@@ -1,11 +1,11 @@
-local uuid = require 'uuid'
 local spawn = ngx and ngx.thread.spawn or coroutine.create
 local wait = ngx and ngx.thread.wait or coroutine.resume

 local promise = {}

 function promise:start(fn)
-  local id = uuid.new()
+  local id = self.next_id
+  self.next_id = self.next_id + 1
   local thread, err = spawn(function()
     return id, fn()
   end)
@@ -65,6 +65,9 @@ function promise:first()

 function exports.create()
-  return setmetatable({threads = {}}, {__index=promise})
+  return setmetatable({threads = {}, next_id = 1}, {__index=promise})
 end
```

**Comment by creationix** [comment]
No, I've not explored implementing promises/futures for luvit since I still think using coroutines is a much better abstraction.  Search https://luvit.io/lit.html#coro for many coroutine-friendly libraries published for luvit.

I'm curious to hear more about the "issues" with this approach and in particular what is meant by "if it could be guaranteed that the thread calling back was able to deal with its execution being interrupted for an unknown amount of time"

**Comment by urzds** [comment]
> I'm curious to hear more about the "issues" with this approach

@rphillips mentioned something on IRC. I quoted that for you on IRC.

> and in particular what is meant by:

> > if it could be guaranteed that the thread calling back was able to deal with its execution being interrupted for an unknown amount of time"

By pushing a `coroutine.yield()` as a callback into the I/O thread, I am interrupting it. I also don't see in the examples that it's execution is somehow continued using `coroutine.resume()`. Thus the I/O thread apparently stalls for an unknown amount of time, until someone resumes it. This could probably lead to all kinds of weird behaviour, like I/O and especially network time-outs, dropped connections, and the like.

Regarding the thread resumption: I assume that there is some scheduler, which does that on a regular basis? But I also assume that there is no control over the timespan until it tries that?

**Comment by creationix** [comment]
Remembering to resume a coroutine is no different an issue than remembering to call a callback.  Both are suspending program flow and then continuing it later.

There is no central thread scheduler other than libuv's own callback based event loop.  The places where I use coroutines in place of explicit continuations in the form of callback functions still use a callback at the lowest level because that's the interface with libuv.

For a simple example, see this implementation of sleep.

```lua
local function sleep(ms)
  local thread = coroutine.running()
  setTimeout(ms, function ()
    coroutine.resume(thread)
  end)
  coroutine.yield()
end
```

Anyone calling this function will be suspended and then resumed later after a given amount of ms.

**Comment by urzds** [comment]
What I mean is: When libuv calls the callback, it will halt execution of its own thread and instead continue in another thread. Now there is the callback thread running and the libuv thread paused. The libuv thread will never be resumed, as far as I can see.

**Comment by creationix** [comment]
I'm not sure what you mean by libuv's thread?

Let's clarify terms.  As far as OS threads, there is only one.  Libuv is single threaded as is a normal luvit program.  We're working on adding multi-threading support, but in general, the event loop is single threaded.

Lua calls it's coroutines "threads" and even uses that as the return for `type(coroutine.running())` which is `"thread"`.  But this is not an operating system thread, it's more like a green-thread.  Libuv knows nothing about these.  All "threads" after this will be talking about lua coroutines, not system threads.

All callbacks in luv happen in the main lua "thread".  This is done because the "thread" that started the async action will sometimes be suspended waiting for the action to complete.  The main thread cannot be suspended by design of the lua language.  The main lua thread and only os thread is blocked by `uv.run()` which is what actually calls the callbacks.

When libuv calls into the main lua thread it will then often resume the other thread as in my simple example.

The `sleep` function is called from within a coroutine which sets up the libuv timeout and then suspends itself using `coroutine.yield()`.  When the timeout expires, libuv will call the embedded lua callback in the main lua thread (not in the coroutine that called `setTimeout`) which then resumes the suspended thread.

**Comment by creationix** [comment]
So what I mean is that there is little difference between the semantics of:

```lua
print("Hello")
setTimeout(1000, function ()
  print("World")
end)
```

and

```lua
print("Hello")
sleep(1000)
print("World")
```

Both run the same risk of the continuation never being resumed.  If `setTimeout` never calls it's callback, then the "world" is never printed.  Likewise, it `sleep` suspends the calling coroutine and then never resumes it, the "world" is never printed.  The danger is the same, but the code clarity of the second style is worlds easier to reason about in most cases.

**Comment by creationix** [comment]
> When libuv calls the callback, it will halt execution of its own thread and instead continue in another thread

The code that calls `coroutine.resume(thread)` will eventually resume.  This happens when the coroutine it resumed either runs to completion and unwinds (like a normal function call) or suspends itself somewhere.  In either case, the main coriutine/thread is never blocked waiting for I/O.

**Comment by pyros2097** [comment]
Great Description on the coroutine based integration with libuv. This needs its own blog post.

**Comment by aiverson** [comment]
What is the recommended equivalent of the any and all operations of promises?
The all operation of promise is convenient because it permits multiple operations to happen in parallel then their results combined. The naive implementation using coroutines only performs one of the three operations at once and waits for completion before starting the next one. In cases where the operations are mostly waiting for IO, like fetching from a remote server, this is a major slowdown.

```
local val1 = operation1coro(arg1)
local val2 = operation2coro(arg2)
local val3 = operation3coro(arg3)

--do stuff
```

The promise version can take advantage of the parallelism but looks uglier.

```
Promise.all(
  operation1promise(arg1),
  operation2promise(arg2),
  operation3promise(arg3)
):then(function(val1, val2, val3)
  --do stuff
end)
```

Is there a recommended solution to accomplish that action with integration to the coroutines? To allow code something like this?

```
local val1, val2, val3 = allCoro(
  {operation1, arg1},
  {operation2, arg2},
  {operation3, arg3})
--do stuff
```

And similarly with any, which allows multiple operations to race and ignores the ones that don't finish first or fail.

Is there a clean recommended solution for this other than implementing the behaviour on top of the callback API at every place it is used? If there isn't any such solution, can there be one added?

**Comment by squeek502** [comment]
@aiversion see coro-split: https://github.com/luvit/lit/blob/master/deps/coro-split.lua

**Comment by creationix** [comment]
I've not needed a promise.any alternative, but as you can see from the coro-split source, it's not hard.

**Comment by aiverson** [comment]
That is exactly what I was looking for. Thank you.
