### ISSUE TITLE
JSON.stringify({}) returns an empty array

### ISSUE THREAD

**Issue by joerg-krause** [luvit/luvit#856]
json.stringify({}) return an empty array instead of an emtpy table:

test-json.lua:

``` lua
local JSON = require ("json")
print(JSON.stringify({}))
```

Output:

``` sh
$ luvit test-json.lua
[]
```

Node.js returns an empty array for:

``` js
console.log(JSON.stringify({}))
```

Output:

``` sh
$ node test-json.js
{}
```

Looking at `json.lua` https://github.com/luvit/luvit/blob/master/deps/json.lua#L308 sets `isa` as `true` and `n` as `0`. The test in the next line fails, because `valmeta = getmetable({})` is `false`.

What can we do about it?

**Comment by kaustavha** [comment]
Just my 2 cents here but shouldnt both those examples ideally return `''` so an empty string? That makes intuitive sense to me.
Also it actually returns a string, arrays dont exist in lua, only tables.
```
> type(json.stringify({}))
'string'
> json.stringify({})
'[]'
```

**Comment by joerg-krause** [comment]
It's correct that `json.stringify()` returns a JSON object as a string.

Arrays (`[]`) exist in JSON, as well as JSON objects (`{}`). As Lua does not have an array type, the JSON encoder must decide, when to encode a Lua table as a JSON object, and when as a JSON arrary.

**Comment by squeek502** [comment]
From [the documentation of the JSON parser used](http://dkolf.de/src/dkjson-lua.fsl/wiki?name=Documentation):

> **`<metatable>.__jsontype`**

> `__jsontype` can be either `"array"` or `"object"`. This value is only
checked for empty tables. (The default for empty tables is `"array"`).

**Comment by joerg-krause** [comment]
The problem is that any empty table gets turned into `"[]"`.

`json.stringify({ test = {} })` should return `{"test":{}}`.

Node does:
```sh
$ node -e "console.log(JSON.stringify({ test : {} }))"
{"test":{}}
```

I've also checked how lua-cjson handles this:
```lua
local cjson = require "cjson"
print(cjson.encode({}))
print(cjson.encode({ test = {} } ))
```
Output:
```sh
{}
{"test":{}}
```

**Comment by rjemanuele** [comment]
Hi Jorg,

This is mostly a Lua issue.  Lua doesn't distinguish between tables and
arrays therefor when translating to json it lust assumes array.  Many
people get around this when they absolutely need a table by including a
dummy value like {dummy = 1}.

It is not perfect by meets the needs of most folks.

--Rob

**Comment by squeek502** [comment]
@rjemanuele, it can be fixed (if you want it to be fixed) by treating empty tables as objects by default instead of arrays. Should just be able to flip the conditionals of [this line](https://github.com/luvit/luvit/blob/master/deps/json.lua#L309) to:

```lua
    if n == 0 or (valmeta and valmeta.__jsontype == 'object') then
      isa = false
    end
```

**Comment by rjemanuele** [comment]
Yes we can change the default behavior.  I'm not sure we want to.  We have
history of empty tables being arrays when translated to JSON.  Is there an
overwhelmingly compelling reason or justification to change it (as the
change will break code for others that rely on the current assumption)?

**Comment by joerg-krause** [comment]
@rjemanuele I am porting some of my Node.js modules to Luvit. The behaviour of Node.js is to return `"{}"` for empty objects. Since Luvit claims itself to implement a Node.js style API, I think we should set the default behaviour to act like Node.js and offer an user option to change the behaviour.

@squeek502 The json library (http://dkolf.de/src/dkjson-lua.fsl/home) used, offers the ability to use a metatable with a `__tojson` function to define custom encoding. I think, if we want to change the bevaviour, we should use this.

**Comment by squeek502** [comment]
@joerg-krause if the goal is to avoid altering the dkjson implementation, then it'd be more straightforward to use a metatable with `__jsontype` set to `"object"` instead (see my quote of the documentation above). But, either way, that would require iterating the entire depth of the table upfront in order to add a metatable to all empty tables found, right?

**Comment by joerg-krause** [comment]
@squeek502 You're right! A quick solution I tried is:

```lua
local json = require("json")

json.stringify = function (value, state)

  jsontype = function (t)
    if type(t) == "table" then
      setmetatable(t, { __jsontype = "object" })
      for _,v in pairs(t) do
        if type(v) == "table" then
          setmetatable(v, { __jsontype = "object" })
          jsontype(v)
        end
      end
    end
  end

  if type(value) == "table" then
    jsontype(value)
  end
  return json.encode(value, state)
end

local t = { a = { }, b = { 1 }, c = { d = { e = {} } }, f = { "string" } }

print(json.stringify(t))
```

**Comment by squeek502** [comment]
That has the potential to clobber existing metatables, though, doesn't it?

```lua
local customTable = setmetatable({}, { __tojson = function() return "test" end })
json.stringify(customTable)
```

would return `{}` when it should return `test`?

**Comment by joerg-krause** [comment]
As Lua does not have an array type, I would like that `json.stringify({})` handles `"{}"` as an object by default instead of an `"array"`.

I understand that the json encoder has to make a descision whether `"{}"` represents an empty object or an empty array. The dkjson library defaults to an empty array, so I have to use a metatable to define that `"{}"` represents an object.

However, using something like `t = setmetable({ }, __jsontype = "object")` all the time I define an object I want to encode to JSON is much more a pain than defining an array explicitly with `a = setmetable({ }, __jsontype = "array")`, just because objects are quite more used than arrays.

Furthermore, I'd like to behave Luvit like Node.js so that `a = {}; json.stringify(a)` returns the same string in both engines.

This means the default behaviour of the json module has to be changed, which means API breakage. But each Luvit module has an own version number, so we could change the version to 3.x.

**Comment by creationix** [comment]
So the reason I prefer defaulting to `[]` instead of `{}` is because it doesn't matter in lua, they are the same thing.  You can parse either and will get an empty table.  But in JS it does matter and the difference is `[]` is a superset of `{}`.  Therefore it's safer to give someone an array when they expected a plain object than to give them a plain object when they expected an array.  You can do `[].foo = true`, but you can't do `({}).push(foo)`.  In other words, an array is an object, but not all objects are arrays.

**Comment by joerg-krause** [comment]
I understand your point of view. On the other hand, Luvit wants to offer a Node.js like API. Currently, I am porting a Node.js app to Luvit. The app uses a defined JSON API to communicate with third party apps, which are not written in Lua.

The ugly part is, that I'll have to add a metatable to every table I want to use as a JSON object, just to get the default behaviour of Node.js or other JSON libraries (e.g. lua-cjson).

Maybe, we could offer a user setting to allow overriding the default behaviour?

**Comment by creationix** [comment]
A setting to choose which it picks is fine, there is no good solution here because the language isn't 1-to-1 with JSON

Now the other problem you'll run into is lua tables are unordered and many existing JSON APIs expect keys to be in a certain order.  Again there is nothing a JSON encoder in lua can do for you here with extra information (such as the preferred order for the keys).

Also if a lua table has `nil` as a value, the key goes away, while in JS and JSON, `null` values are perfectly valid.  We do work around this with the special `null` constant in the library, but then the decoder needs to choose between killing the key or inserting the `null` constant when a `null` is found in JSON.  Removing the key can break for some people and using the truthy special constant can break for others.

Using JSON in lua is rife with problems if you want to use vanilla lua tables without any extra metadata.

**Comment by creationix** [comment]
Now for parsing JSON, it's possible to make a special lua table that has both ordered keys and iterates over keys pointing to `null` values by placing extra metadata in the metatable and using the `__pairs` metamethod.  Users of the library probably don't even notice this behavior and will assume it's a normal lua table.  The tricky side is the encoder simply doesn't have enough information to know if `{}` in lua should be `[]` or `{}` in JS.  It doesn't know you meant to include key `foo` when the value was nil, and it really has no way to know what order you want the keys to be in.

While adding a config option to set the default assumption for `[]` vs `{}` will help some, you'll still hit the other issues and end up needing extra metadata.

I'm sorry JSON is harder to use in lua vs JS, but remember JSON is based on JS.  Any other language will have some mismatch with the native semantics of the language.

Just be glad you're not trying to consume JSON with a static typed language like Java.  We could add the kind of iterative API that's used in these static languages and you can build the object piecemeal a property and node at a time with a moving cursor through the object.

**Comment by creationix** [comment]
In other words, I'm not opposed to adding a new option to change the global default behavior.  I'm just concerned you'll hit other issues down the road and it won't actually help.  The library already has a metadata based way to specify which to use. 

If you're sure all you need is this new global option, I'll see about adding it.  I just don't want to add something that doesn't end up helping.

**Comment by joerg-krause** [comment]
Using ordered keys is arguable. The [JSON RFC](www.rfc-editor.org/rfc/rfc7159.txt) does not define it to be ordered:
> An object is an unordered collection of zero or more name/value
   pairs, where a name is a string and a value is a string, number,
   boolean, null, object, or array.

As for nil and null I would follow the JavaScripts implementation: skip nil values and use null in arrays.

For me and maybe others coming from Node the advantage of mapping `{}` to an object by default and use a metatable for mapping it to an array is to ease migration. Curly braces are used for objects in many languages and square brackets for arrays. Okay, Lua does not have arrays and objects, just tables. But it is more obvious for me that the curly braces from Lua maps to an JSON object as it maps to an array

For example:
```lua
t = {
  a = {},
  b = setmetatable({}, __jsontype = "table"),
  c = nil
}
print(JSON.stringify(t))
{ "a" : {}, "b" : [] }
```

**Comment by creationix** [comment]
I understand that the RFC says they shouldn't be ordered, but that doesn't matter when you're trying to consume a service that requires ordered keys.  I've been hit by this many times in real use cases.  

The fact is that all JS implementations preserve order of keys and have for many years.  While it's not in the spec, nobody dares to ever change the behavior because of the vast number of websites it would break.  For all intents and purposes, keys are ordered in JS and JSON.

I understand that lua's `{}` looks a lot like JS's `{}`.  But the lua version of JS's `[]` happens to also be `{}`.  In my experience, an empty table more often is used as an empty list than an empty object.

You're asking me to change the default behavior, because in your use case, it's more convenient to assume `{}` means object and not array.  But as the maintainer I have to worry about all use cases and the people's workflows that will be broken by changing the default behavior.  Technically speaking, sending an empty array to JS when it expects an empty object is less likely to break things than sending an object when it expects an array (because arrays are a superset of objects in JS).

I've already said I'm willing to add a feature where you can set a new default behavior globally for your instance of the JSON encoder and we already have the feature in stable luvit where you can specify per-table using a metamethod.

I've also warned about two other possible places where inter-operating with JSON services will be tricky in lua.  Unless you're sure that the problem of empty-array vs empty-object is the only place you'll have friction, you're going to need metatable metadata anyway and so there is no point in adding the new global config option. (Also what if you use some library that uses JSON internally and assumes the default to be something else, global settings are dangerous)

**Comment by creationix** [comment]
> As for nil and null I would follow the JavaScripts implementation: skip nil values and use null in arrays.

I'm not sure what you're proposing here.  There is no `nil` in JS and no `null` in Lua.  JavaScript does not skip `null` values, this is where the problem comes in.  In lua, the way to delete a property is to set it to `nil`.  Otherwise lua's `nil` and JS's `null` work more or less the same.

```js
> JSON.stringify({name:null})
"{\"name\":null}"
> JSON.stringify([1,null,2])
"[1,null,2]"
```

```lua
> JSON = require('json')
> {1,nil,2}
{ 1, [3] = 2 }
> JSON.stringify({1,nil,2})
'[1,null,2]'
> {name=nil}
{ }
> JSON.stringify({name=nil})
'[]'
```

**Comment by creationix** [comment]
As you can see, we already fill in holes in arrays with `null` automatically, but you have to specify if you want an object with null values or an empty object.

**Comment by joerg-krause** [comment]
> I understand that the RFC says they shouldn't be ordered, but that doesn't matter when you're trying to consume a service that requires ordered keys. I've been hit by this many times in real use cases.

> The fact is that all JS implementations preserve order of keys and have for many years. While it's not in the spec, nobody dares to ever change the behavior because of the vast number of websites it would break. For all intents and purposes, keys are ordered in JS and JSON.

I'm fine with that the JSON library used in Luvit does not order keys. I wasn't really aware that JS does.

> I'm not sure what you're proposing here. There is no nil in JS and no null in Lua. JavaScript does not skip null values, this is where the problem comes in. In lua, the way to delete a property is to set it to nil. Otherwise lua's nil and JS's null work more or less the same.

Sorry, I did not meant to propose anything about nil and null. What I meant is that a nil value in Lua should be skipped in JSON unless it is a value in an array where it should be represented as null. This is already handled this way in Luvit.

> You're asking me to change the default behavior, because in your use case, it's more convenient to assume {} means object and not array. But as the maintainer I have to worry about all use cases and the people's workflows that will be broken by changing the default behavior. Technically speaking, sending an empty array to JS when it expects an empty object is less likely to break things than sending an object when it expects an array (because arrays are a superset of objects in JS).

When I started migrating a Node.js project to Luvit I was amazed how similar the API is. It really makes fun to re-code in Luvit, because I can look at the Node.js API and implement it (almost) the same way in Luvit. However, there are some parts in Luvit where I stumbled. One of this is `JSON.stringify({})`.

I also understand that a JSON library has to make decisions how it implements these things. cjson implements stringify in a different way then dkjson does. I also know that there are some uncertain and arguable points about how to use JSON in practice, e.g. how should empty values be represented: skip the value? null? empty object? empty array?

I started the discussion from an API point of view. Luvit says "Luvit implements the same APIs as Node.js, but in Lua! This helps teams migrate without having to learn a new way of programming." For me, this means I can write `JSON.stringify({})` and I get the same result in both engines and not have to use `JSON.stringify(setmetatable({},{__jsontype="object"}))` in Luvit.

My intention is not to change the default behaviour of the JSON encoder globally, I understand the risk of breaking existing systems.

**Comment by creationix** [comment]
Right, I guess my main issue is that `JSON.stringify({})` does not mean the same thing in the same two languages.  Yes it looks identical and in some cases is identical, but for reasons previously mentioned, an empty table is rather different from an empty object as far as a JSON encoder is concerned.

So what can I do to help you?  Just document the gotcha about needing `__jsontype` when encoding empty objects?  Add an option somewhere to change the default behavior through some other means?  This could maybe be in the call to `JSON.stringify({}, {jsontype="object"})` or something?

**Comment by joerg-krause** [comment]
I really appreciate it if you can document this.

I'm not sure how to do it right. What do you think about an option to set for an instance of a json module how it should treat empty tables: as JSON objects or JSON arrays?

**Comment by creationix** [comment]
That could be an option, allow instances of the JSON object with certain defaults set.  Then you don't affect other modules and it's still global for your file.

```lua
local JSON = require('json').configure({jsontype="object"})
...
```

And then docs for this and the default behavior.

**Comment by joerg-krause** [comment]
LGTM! Just one nitpick: clarify that it is a default type. Maybe one of this:
```lua
local JSON = require('json').configure({jsontypedefault="object"})
local JSON = require('json').configure({defaultjsontype="object"})
```

Many thanks for taking care of this!

**Comment by SinisterRectus** [comment]
I know this is over a year old and this isn't the main topic, but you can specify a key order in this json module.

**Comment by joerg-krause** [comment]
Closing this issue as I am get used to use the `__jsontype` parameter to set an empty value to `{}`.
