### ISSUE TITLE
A question about require

### ISSUE THREAD

**Issue by Miigon** [luvit/luvit#868]
There are two files:*"./utils.lua"* and *"./foo/bar.lua"*
How can I require *"utils.lua"* in *"bar.lua"*?(starting directory of luvit is *"./"*)

**Comment by creationix** [comment]
With luvit's require system, the cwd doesn't matter at all, only the relative paths of the calling file and the file it wants to require.

So from `foo/bar` you would require `utils` as `../utils`.

We also have a system for libraries so that you don't need to know the exact relative path between all modules.  If you put utils in a `libs` folder you can just load it as `utils` without the relative path at the front.

So `foo/bar.lua` can just do `require("other")` which is in `libs/other.lua`.

(I should note that `utils` is a built-in library in luvit and as such will shadow any on-disk libraries by the same name.  You can still get to `utils.lua` via the relative path, but not via the `libs/utils.lua` using `utils`.)

**Comment by xpol** [comment]
Will the luvit's require system change when the [luvit-loader.lua](https://github.com/luvit/luvit/blob/luvly/luvit-loader.lua) is ready?

Or when luvit-loader is ready, will the both require system works at the same time?

**Comment by Miigon** [comment]
In fact,Luvit's require system brings a lot of compatibility issues I have to solve

**Comment by creationix** [comment]
luvit-loader is just a normal lua loader that implements the luvit style relative requires.  It will still support looking for modules in "libs" and "deps" as well as resolve relative paths starting with ".".

Also the new lit metadata style using a comment instead of assuming globals will help compatibility issues as well.  This is already out there in lit 3.0 and it supports either format.  The luvit require system can consume new-style modules no problem since they just return the exports.  This is supported by virtually all lua require systems.

The only issue slowing down migration is luvit-loader doesn't support old-style lit metadata.  If I replace luvit/require with luvit-loader then it will be no longer able to load about 95% of the existing published luvit modules.

**Comment by creationix** [comment]
@Miigon is there anything in particular that's causing you trouble?  Will these changes help any?
