### ISSUE TITLE
Nodejs os.networkInterfaces() in luvit?

### ISSUE THREAD

**Issue by xpol** [luvit/luvit#879]
Is there any nodejs' `os.networkInterfaces()` or equivalent in luvit?

**Comment by creationix** [comment]
Yep, it's built into libuv.

So do:

```lua
> require('uv').interface_addresses()
{
  awdl0 = {
    { netmask = 'ffff:ffff:ffff:ffff::', ip = 'fe80::182c:88ff:fe84:f68b', family = 'inet6',
      internal = false, mac = '\026,\136\132\246\139' } },
  en0 = {
    { netmask = 'ffff:ffff:ffff:ffff::', ip = 'fe80::3e15:c2ff:fedc:1ca', family = 'inet6',
      internal = false, mac = '<\021\194\220\001\202' },
    { netmask = 'ffff:ffff:ffff:ffff::', ip = '2601:643:8000:dfe:3e15:c2ff:fedc:1ca',
      family = 'inet6', internal = false, mac = '<\021\194\220\001\202' },
    { netmask = 'ffff:ffff:ffff:ffff::', ip = '2601:643:8000:dfe:f852:a3f7:c188:9954',
      family = 'inet6', internal = false, mac = '<\021\194\220\001\202' },
    { netmask = '255.255.255.0', ip = '10.0.0.64', family = 'inet', internal = false,
      mac = '<\021\194\220\001\202' } },
  lo0 = {
    { netmask = 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff', ip = '::1', family = 'inet6',
      internal = true, mac = '\000\000\000\000\000\000' },
    { netmask = '255.0.0.0', ip = '127.0.0.1', family = 'inet', internal = true,
      mac = '\000\000\000\000\000\000' },
    { netmask = 'ffff:ffff:ffff:ffff::', ip = 'fe80::1', family = 'inet6', internal = true,
      mac = '\000\000\000\000\000\000' } } }
```
```

**Comment by kaustavha** [comment]
You can also use sigar like its done here:
https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/blob/master/hostinfo/network.lua
to get a bit more data, e.g:
https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/blob/master/hostinfo/debug/NETWORK.json
Luvit allows you to very easily use libuv so if you look at the nodejs code:
https://github.com/nodejs/node/blob/master/lib/os.js#L15
That's the os module, highlighting how they getNetworkInterfaces, they basically just bind the libuv networkaddresses endpoint. You can search around the libuv docs for the name
http://docs.libuv.org/en/v1.x/misc.html?highlight=os#c.uv_interface_address_t
and playing around with luvit in the command line you can basically discover something that lets you do that within the uv module which can be surfaced with `uv = require('uv')`


@creationix Do you think we should perhaps add docs for libuv to the luvit api docs and mention this in the luvit,io/docs page? Additionally the CLI auto-includes everything in luvit/lib, do you think it'd be prudent to also auto include libuv as `uv`

**Comment by joerg-krause** [comment]
What I've learned so far by using lockout is that there are many ways howto do something, eg. using streams. I would appreciate to have some guidelines or best practices when to use libuv, luvit or even ffi.

**Comment by kaustavha** [comment]
luvit > libuv > ffi
Thats my thoughts. 
FFI is pretty fast in lua but still incurs some overhead.
Luvit is pretty much just a wrapper around libuv at times, so the difference between the two is minor. 
I personally believe if you find yourself using libuv, e.g. this case, you should go back and open a pr to luvit which extends it similiar to nodejs with the functionality that you required from libuv and expected in the first place. Luvits api is similiar to nodejs and the main author has expressed he would like it to be as similiar to nodejs as possible where it makes sense and is an improvement, not a regression.
Theres a lot of functionality that was left unwrapped but still usable easily by requiring libuv since well the main authors merely human and doesnt have the time or omniscience to include everything from libuv people might require.

The streams vs coroutines vs callbacks debate is kinda moot, they can all perform fairly well and comes down to the programmers choice. try new things, see what you like. Creationix prefers coroutines afaik, i prefer callbacks, streams are sometimes faster (good example is fs.appendFileSync vs using a stream, appendfilesync is slow since it constantly opens new filedescriptors and closes them) but may result in more code, but may also be more readable at the end of the day.

**Comment by xpol** [comment]
Here is my current solution with luv:

```lua
local familys = {
  v4 = 'inet',
  v6 =  'inet6'
}
local ipaddress = {}
function ipaddress.get(version)
  local family = familys[version or 'v4']
  local ips = {}
  for k, v in pairs(require('uv').interface_addresses()) do
    if not k:find('bridge%d*') then
      for _, iface in ipairs(v) do
        if iface.internal == false and iface.family == family then
          ips[#ips+1] = iface.ip
        end
      end
    end
  end
  return ips
end

setmetatable(ipaddress, { __call = function(_, ...) return ipaddress.get(...) end })

return ipaddress
```

**Comment by creationix** [comment]
@kaustavha actually with luajit 2.0, ffi is part of the actual jit engine so there is no overhead.  It just emits the code along with the generated native code from the jit tracing.  This is unlike other languages where FFI has a fairly high cost because it needs to go through layers of C APIs.

**Comment by kaustavha** [comment]
:o neat
