### ISSUE TITLE
child process command issues

### ISSUE THREAD

**Issue by Kumar-Patil** [luvit/luvit#901]
Hi All,

i am new to luvit ,

Please help to resolve issue.

local child = require("childprocess.lua")
local cmd = "boundary-meter --rpc " .. '\'' .. '{"jsonrpc":"2.0","id":1,"method":"discovery","params":{}}' .. '\''
local std = child.exec(cmd,print)

if i pass the custom function in above called method. i will get the output as empty. if i pass as print it will print output  in command line.
1. if i execute below code 
   local command = "echo " .. '{"jsonrpc":"2.0","id":1,"method":"discovery","params":{}}' .. " | nc 127.0.0.1 9192"
   local proc = child.spawn(command, {}, {})
   proc.stdout:on('data',
       function (data) output =  data
       print("why null")
       print(data)
       print(output)
      end)
   I will get output as empty.

If i run same thing in command line it will give proper output.

In any above condition we need store output in local variable. is it possible ?

Please help me to resolve issue.

Thanks&Regars
Santosh Patil

**Comment by creationix** [comment]
The core/legacy luvit APIs are modeled after node.js.  You can see the node docs for exec at https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback

In node, the stdout and stderr are returned via variables in the continuation callback.  The luvit version appears to be the same. https://github.com/luvit/luvit/blob/master/deps/childprocess.lua#L236

Though since lua has coroutines, you don't need to use the legacy interface and can instead use coroutines.  The legacy exec supports this by passing in the thread in place of a callback.

```lua
coroutine.wrap(function ()
  local thread = coroutine.running()
  local stdout, stderr = exec("ls", thread)
end)()
```

Or you can use the creationix/coro-spawn library that's published to lit.  Install it in your project by adding it to your dependencies and running `lit install` or install it directly witth `lit install creationix/coro-spawn`.

An example or using coro-spawn and coro-split to implement a coroutine based exec can be seen in the lit source. https://github.com/luvit/lit/blob/master/libs/exec.lua

**Comment by Kumar-Patil** [comment]
Thanks creationix.
