### ISSUE TITLE
Cannot find module 'core' from user-defined module while using luvit.

### ISSUE THREAD

**Issue by JoeBmc** [luvit/luvit#929]
Hi,

I have build luvit locally on an RHEL 64-bit machine. Now luvit is available in the command prompt.
I am using luvit <filname.lua> to run a particular application.
$pwd
/root/lua/plugin/meter-plugin-fork-rate
$luvit init.lua

If I have a require instruction as below in the file init.lua it picks up the module correctly (no error thrown)
         local core = require('core')
         
But if I do the same thing in my own module, then I get an error saying
         ./framework.lua:23: module 'core' not found:

init.lua          
          local framework = require('framework')

framework.lua
          local core = require('core')

Both framework.lua and init.lua are in the same folder.

package.path
./?.lua;/usr/local/share/luajit-2.1.0-beta2/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua

package.cpath
./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so

Full error stack
Uncaught exception:
[string "bundle:deps/require.lua"]:278: No such module 'framework' in '/root/lua/plugin/meter-plugin-fork-rate/init.lua'
./framework.lua:23: module 'core' not found:
        no field package.preload['core']
        no file './core.lua'
        no file '/usr/local/share/luajit-2.1.0-beta2/core.lua'
        no file '/usr/local/share/lua/5.1/core.lua'
        no file '/usr/local/share/lua/5.1/core/init.lua'
        no file './core.so'
        no file '/usr/local/lib/lua/5.1/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        [string "bundle:deps/require.lua"]:278: in function 'require'
        /root/lua/plugin/meter-plugin-fork-rate/init.lua:24: in function 'fn'
        [string "bundle:deps/require.lua"]:309: in function 'require'
        [string "bundle:main.lua"]:118: in function 'main'
        [string "bundle:init.lua"]:49: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>

1. Is there something I am missing to make it work.
2. How to find the path from where the module was picked up.(in the case when it is resolved)
3. I assume that the luvit (executable/command) have all the dependencies embedded. Why luvit is not able to resolve the module dependency?
4. Can I add my own module to luvit by adding the same to the deps folder before building it ?

regards,
Jose

**Comment by JoeBmc** [comment]
Tried require ('../core') does not work.

**Comment by JoeBmc** [comment]
I was able to solve the issue by making the following changes.
$pwd
/root/lua/plugin/meter-plugin-fork-rate
mkdir modules
mv framework.lua ./modules/

init.lua
require('./modules/framework')

./modules/framework.lua
require('core')

Working fine and 'core' module is resolved. But not sure why it fixed the issue.

**Comment by squeek502** [comment]
Able to reproduce this issue on Windows. There's definitely something weird going on, as the error message shows two conflicting missing package names:

```
[string "bundle:deps/require.lua"]:278: No such module 'framework' ...
./framework.lua:23: module 'core' not found:
```

**Comment by squeek502** [comment]
I think I figured out what's going on.

- The `require('framework')` call in `init.lua` uses Luvit's require, which looks in the luvi bundle first, then checks `libs` and `deps` directories (recursively on all parent directories of the current file), and if neither of those succeed, then it falls back to the native Lua require.
- 'framework' fails the Luvit require checks, and when it falls back to the Lua require, it doesn't set up the same environment as it would for a Luvit-resolved module, and so when `require` is called in `framework`, it will also use the native Lua require. Luvit's require doesn't populate `package.loaded`, so Lua's require will fail to load bundled dependencies no matter what.

So, for solutions:

- Move the files you're requiring into a `libs` folder. `require('framework')` will work if `framework.lua` is inside a `libs` directory.
- Use relative requires, as Luvit has special handling for that which also bypasses the native Lua require (note that `require('./framework')` would also work without having to move `framework.lua`)

As for whether or not this is a bug, I can't be sure. It could be fixed by modifying the environment of the native require fallback similar to how Luvit's require does it for modules it loads, but I'm not sure what exactly the ramifications of that would be.

**Comment by JoeBmc** [comment]
Thanks for the reply.
I will try what you suggested. thanks again.

**Comment by creationix** [comment]
Once the fallback path is reached, I'm not touching the require environment.

Ideally we'd just switch to the new luvit require system that is a lua require loader instead of the current one that modifies local environments.

The problem is, if I make this change in luvit itself, it's a pretty large breaking change for some nasty edge cases.

Should I just release a new major version of luvit that drops all the legacy support and does things cleanly? (I also need to remove many of the standard libraries now that we have the lit module system and all luvit standard libraries have been published there for some time)

**Comment by JoeBmc** [comment]
Thanks Tim.
We took the standard folder approach suggested by squeek502. That resolved the issue.

Moving to new luvit require would be great - as it is always confusing on why the bundled dependencies are not resolved when we fall back to native lua require.
