### ISSUE TITLE
problem with "require" in submodules

### ISSUE THREAD

**Issue by jkralacrobits** [luvit/luvit#981]
Hi,

I have `main.lua` like this:
```
local utils = require('utils')
local myModule = require("test_module")
.......
```
my `test_module.lua` is in the same directory as `main.lua` and it contains:
```
local timer = require('timer')
.....
```

when I run `luvit main.lua`, it complains that it can't  load `timer` from within `test_module.lua`, but it loads `utils` from main.lua without problems.
```
./test_module.lua:1: module 'timer' not found:
	no field package.preload['timer']
	no file './timer.lua'
	no file '/usr/local/share/luajit-2.1.0-beta2/timer.lua'
	no file '/usr/local/share/lua/5.1/timer.lua'
	no file '/usr/local/share/lua/5.1/timer/init.lua'
	no file './timer.so'
	no file '/usr/local/lib/lua/5.1/timer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

What is the right way to "require" 3rd party modules from my own modules?

**Comment by creationix** [comment]
If you want to require relative files, use relatve paths starting with `.`.  For example

```lua
local myModule = require("./test_module")
--...
```

Also you can take advantage of the `deps` and `libs` resolution strategy.  This is what `lit` uses when it installs 3rd party libraries.

So move `test_module.lua` to `libs/test_module.lua` and then you can require is as just `test_module` from anywhere within your file tree.

The `libs` and `deps` folders work identically, the difference is `deps` is managed by the `lit` package manager and `libs` is for things you manage manually (any typically include with your codebase)

**Comment by creationix** [comment]
So what's happening here is luvit's require can't find the file since you didn't use a relative require or put it in the deps or libs folder.  The fallback then is to use lua's native require which does look in the current folder by default.  But since your module was loaded by lua's native require further requires inside of it are not able to use the luvit extensions (like the built-in luvit libraries that are actually embedded in a zip appended to the `luvit` binary)

Luvit modules can require lua modules, but lua modules can't require luvit modules without some manual re-bootstrapping.

**Comment by jkralacrobits** [comment]
Thank you, now it works like a charm. I put my modules into `libs`.
